name: unit tests and code-coverage
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - name: Run unit tests and code-coverage
        run: |
          go test -race -covermode=atomic ./...